# Fourier Slope/Sigma

In [3]:
import os
import time
import pandas as pd
from PIL import Image
import numpy as np

# Import your functions
from utils.AT.fourier_qips import fourier_redies as fourier_qips_func
from utils.AT.fourier_modified import fourier_redies as fourier_modified_func

# Folder with input images
image_folder = r"C:\Users\20225378\Desktop\IDEAS final\Images\office"
n_images = 10
# Store results
results = []

# Loop through images
for filename in os.listdir(image_folder)[:n_images]:
    if filename.lower().endswith((".png", ".jpg", ".jpeg", ".bmp", ".tiff")):
        file_path = os.path.join(image_folder, filename)

        # Load image
        img = Image.open(file_path).convert("L")
        img_array = np.array(img)

        # ---- First function ----
        start_time = time.time()
        result_qips = fourier_qips_func(img_array)
        time_qips = time.time() - start_time

        # ---- Second function ----
        start_time = time.time()
        result_modified = fourier_modified_func(img_array)
        time_modified = time.time() - start_time

        # Store results
        results.append({
            "image": filename,
            "result_qips": result_qips,
            "time_qips_sec": time_qips,
            "result_modified": result_modified,
            "time_modified_sec": time_modified
        })

        print(f"Processed {filename}")

# Convert to DataFrame
df = pd.DataFrame(results)

print(f"Mean time original {df['time_qips_sec'].mean()} -- Mean time modified {df['time_modified_sec'].mean()}")
df

Processed office__0.png
Processed office__1.png
Processed office__10.png
Processed office__100.png
Processed office__101.png
Processed office__102.png
Processed office__103.png
Processed office__104.png
Processed office__105.png
Mean time original 5.9157804648081465 -- Mean time modified 0.08123705122205946

,image,result_qips,time_qips_sec,result_modified,time_modified_sec
0,office__0.png,"(0.00972384897343073, -2.681590968793419)",6.242661,"(0.00972384897343073, -2.681590968793419)",0.080030
1,office__1.png,"(0.010729493459103918, -2.664189871391134)",6.117958,"(0.010729493459103918, -2.664189871391134)",0.067951
2,office__10.png,"(0.007480374421108966, -2.6060612067756868)",5.736660,"(0.007480374421108966, -2.6060612067756868)",0.071090
3,office__100.png,"(0.011801540555440021, -2.727020444895154)",5.354506,"(0.011801540555440021, -2.727020444895154)",0.085450
4,office__101.png,"(0.009805743753742022, -2.692831572564168)",6.139092,"(0.009805743753742022, -2.692831572564168)",0.088212
5,office__102.png,"(0.012985356911901839, -3.001931227605733)",6.212242,"(0.012985356911901839, -3.001931227605733)",0.082243
6,office__103.png,"(0.005428981209510864, -2.763521834565117)",6.244020,"(0.005428981209510864, -2.763521834565117)",0.100174
7,office__104.png,"(0.009422484197149372, -2.9555901539731213)",5.670509,"(0.009422484197149372, -2.9555901539731213)",0.081044
8,office__105.png,"(0.0060793602460005106, -2.9211160519861616)",5.524377,"(0.0060793602460005106, -2.9211160519861616)",0.074938

#### First order edge density, second order edge density and edge density comparison

In [4]:
import os
import time
import pandas as pd
from PIL import Image
import numpy as np

# Import your functions
from utils.AT.edge_entropy_qips import do_first_and_second_order_entropy_and_edge_density as edge_density_original
from utils.AT.edge_entropy_modified import first_and_second_order_entropy_and_edge_density as edge_density_modified

# Folder with input images
image_folder = r"C:\Users\20225378\Desktop\IDEAS final\Images\bedroom"
n_images = 10
# Store results
results = []

# Loop through images
for filename in os.listdir(image_folder)[:n_images]:
    if filename.lower().endswith((".png", ".jpg", ".jpeg", ".bmp", ".tiff")):
        file_path = os.path.join(image_folder, filename)

        # Load image
        img = Image.open(file_path).convert("L")
        img_array = np.array(img)

        # ---- First function ----
        start_time = time.time()
        result_qips = edge_density_original(img_array)
        time_qips = time.time() - start_time

        # ---- Second function ----
        start_time = time.time()
        result_modified = edge_density_modified(img_array)
        time_modified = time.time() - start_time

        # Store results
        results.append({
            "image": filename,
            "result_qips": result_qips,
            "time_qips_sec": time_qips,
            "result_modified": result_modified,
            "time_modified_sec": time_modified
        })

        print(f"Processed {filename}")

# Convert to DataFrame
df = pd.DataFrame(results)

print(f"Mean time original {df['time_qips_sec'].mean()} -- Mean time modified {df['time_modified_sec'].mean()}")
df

Processed bedroom__0.png
Processed bedroom__1.png
Processed bedroom__10.png
Processed bedroom__100.png
Processed bedroom__101.png
Processed bedroom__102.png
Processed bedroom__103.png
Processed bedroom__104.png
Processed bedroom__105.png
Processed bedroom__106.png
Mean time original 7.8524682998657225 -- Mean time modified 3.7526659250259398

,image,result_qips,time_qips_sec,result_modified,time_modified_sec
0,bedroom__0.png,"(4.344435855042109, 4.391809070377701, 66.8094...",7.830499,"(4.344435855042109, 4.391809070377701, 66.8094...",4.676405
1,bedroom__1.png,"(3.8550903216741443, 4.054313504273331, 73.138...",8.550519,"(3.8550903216741443, 4.054313504273331, 73.138...",3.856441
2,bedroom__10.png,"(4.0264109099514265, 4.153596888428996, 50.806...",7.597649,"(4.0264109099514265, 4.153596888428996, 50.806...",3.920206
3,bedroom__100.png,"(4.232615052812477, 4.3362710632872075, 58.369...",9.307268,"(4.232615052812477, 4.3362710632872075, 58.369...",3.919413
4,bedroom__101.png,"(3.8120666694390946, 4.108838574993698, 88.054...",8.659646,"(3.8120666694390946, 4.108838574993698, 88.054...",3.361646
5,bedroom__102.png,"(4.295910594284571, 4.368033784357571, 74.3637...",7.807543,"(4.295910594284571, 4.368033784357571, 74.3637...",3.506265
6,bedroom__103.png,"(3.9955069119472926, 4.2341177414868545, 72.19...",6.841375,"(3.9955069119472926, 4.2341177414868545, 72.19...",3.604527
7,bedroom__104.png,"(4.053814904397889, 4.304477883755515, 72.9587...",6.625689,"(4.053814904397889, 4.304477883755515, 72.9587...",3.875193
8,bedroom__105.png,"(4.3221311388913985, 4.3682814416514555, 71.61...",8.170115,"(4.3221311388913985, 4.3682814416514555, 71.61...",3.182304
9,bedroom__106.png,"(3.538382680971004, 3.894938570292498, 97.2072...",7.134381,"(3.538382680971004, 3.894938570292498, 97.2072...",3.624260

#### CNN symmetry comparison

In [5]:
import os
import time
import pandas as pd
from PIL import Image
import numpy as np

# Import your functions
from utils.AT.CNN_qips import CNN_symmetry as symmetry_original
from utils.AT.CNN_modified import CNN_symmetry as symmetry_modified
n_images = 10
# Folder with input images
image_folder = r"C:\Users\20225378\Desktop\IDEAS final\Images\bedroom"
[kernel,bias] = np.load(open(r"utils\AT\bvlc_alexnet_conv1.npy", "rb"), encoding="latin1", allow_pickle=True)

# Store results
results = []


# Loop through images
for filename in os.listdir(image_folder)[:n_images]:
    if filename.lower().endswith((".png", ".jpg", ".jpeg", ".bmp", ".tiff")):
        file_path = os.path.join(image_folder, filename)

        # Load image
        img = Image.open(file_path).resize((224,224))
        img_array = np.array(img)

        # ---- First function ----
        start_time = time.time()
        result_qips = symmetry_original(img_array, kernel, bias)
        time_qips = time.time() - start_time

        # ---- Second function ----
        start_time = time.time()
        result_modified = symmetry_modified(img_array, kernel, bias)
        time_modified = time.time() - start_time

        # Store results
        results.append({
            "image": filename,
            "result_qips": result_qips,
            "time_qips_sec": time_qips,
            "result_modified": result_modified,
            "time_modified_sec": time_modified
        })

        print(f"Processed {filename}")

# Convert to DataFrame
df = pd.DataFrame(results)

print(f"Mean time original {df['time_qips_sec'].mean()} -- Mean time modified {df['time_modified_sec'].mean()}")
df

Processed bedroom__0.png
Processed bedroom__1.png
Processed bedroom__10.png
Processed bedroom__100.png
Processed bedroom__101.png
Processed bedroom__102.png
Processed bedroom__103.png
Processed bedroom__104.png
Processed bedroom__105.png
Processed bedroom__106.png
Mean time original 14.0839173078537 -- Mean time modified 0.38953800201416017

,image,result_qips,time_qips_sec,result_modified,time_modified_sec
0,bedroom__0.png,"(0.3371057252494143, 0.2298364460344121, 0.213...",15.304480,"(0.33710573010944656, 0.2298364507424795, 0.21...",0.418538
1,bedroom__1.png,"(0.29204919677858365, 0.18383274802029825, 0.2...",14.894663,"(0.29204919607792557, 0.1838327482898684, 0.26...",0.434769
2,bedroom__10.png,"(0.3647144925741861, 0.34352486534620974, 0.26...",13.931839,"(0.3647144936436182, 0.34352486587310693, 0.26...",0.400900
3,bedroom__100.png,"(0.3775027594532202, 0.33143468551200794, 0.26...",13.682686,"(0.37750275820063084, 0.3314346869455925, 0.26...",0.365453
4,bedroom__101.png,"(0.3750636682364503, 0.3075455498644144, 0.264...",13.597567,"(0.37506366949321446, 0.307545550997428, 0.264...",0.366312
5,bedroom__102.png,"(0.3955294954128067, 0.3084933421921797, 0.301...",13.590783,"(0.39552949656661573, 0.30849334420906704, 0.3...",0.373595
6,bedroom__103.png,"(0.3277796153940623, 0.3721038347837363, 0.263...",13.726492,"(0.32777961112100107, 0.37210383291819604, 0.2...",0.373420
7,bedroom__104.png,"(0.36896415050657283, 0.40918346586271837, 0.3...",13.900704,"(0.3689641486002354, 0.4091834665108762, 0.341...",0.387146
8,bedroom__105.png,"(0.31193425432630983, 0.32521446204885573, 0.2...",14.111843,"(0.3119342531936723, 0.3252144631742415, 0.265...",0.400917
9,bedroom__106.png,"(0.34899982695431697, 0.3887406116029236, 0.28...",14.098116,"(0.3489998266087804, 0.3887406137182897, 0.284...",0.374330